[project]
name = "stacks-wallet-connection-contracts"
description = "Clarity smart contracts for Stacks Wallet Connection Labs"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.tip-jar]
path = "contracts/tip-jar.clar"
epoch = "latest"

[contracts.tip-jar-v2]
path = "contracts/tip-jar-v2.clar"
epoch = "latest"

[contracts.gas-meter]
path = "contracts/gas-meter.clar"
epoch = "latest"

[contracts.raffle]
path = "contracts/raffle.clar"
epoch = "latest"

[contracts.quest-system]
path = "contracts/quest-system.clar"
epoch = "latest"

[contracts.voting-system]
path = "contracts/voting-system.clar"
epoch = "latest"

[contracts.daily-check-in]
path = "contracts/daily-check-in.clar"
epoch = "latest"

[contracts.dice-game]
path = "contracts/dice-game.clar"
epoch = "latest"

[contracts.rock-paper-scissors]
path = "contracts/rock-paper-scissors.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet

